# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20170214_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=5),
        ),
    ]
